# path to samples table
samples_table: "config/McGarvey2022_samples.csv"
# location of bwa indexed genome for the alignment
bwa_genome: "../GRCz11/GCF_000002035.6_GRCz11_primary_genomic.fna"
# number of threads to use for bwa-mem alignment
bwa_threads: 12
# location of chromosome sizes file (see example in resources folder)
chrom_sizes: "../GRCz11/GCF_000002035.6_GRCz11_primary_genomic.sizes"
# number of processors to use when sorting the pairs file
pairtools_sort_nproc:  8
# gigabytes of memory (##G) to use when sorting the pairs file
pairtools_memory:  "96G"
# path and name of juicer style restriction enzyme file
juicer_RE_file: "../GRCz11/GRCz11_HindIII.txt"
# bin size for .cool file
cooler_bin_size: 10000
# number of cores to use when generating the .cool file
cooler_n_cores: 12
# maximum number of splits of chromosome when generating the .cool file
cooler_max_split: 8
# choose (True or Fase) whether to merge all as sequencing replicates
merge_as_sequencing_replicates: False
# choose (True or False) whether to merge all as biological replicates
merge_as_biological_replicates: True
# merged sample name ("Your_Sample_Name"). All merged files will have this in their name.
merged_sample_name: "SRR12008033_4"
# memory and number of processors for pairtools merge
pairtools_merge_memory: "64G"
pairtools_merge_nproc: 8
juicer_pre_nproc: 8
# select the resolution (bp) for detecting compartments
juicer_eigenvector_resolution: 25000
# select the normalization method used for detecting compartments (NONE/VC/VC_SQRT/KR)
juicer_eigenvector_normalization: "KR"
# chromosomes to detect compartments on
juicer_eigenvector_chromosomes: "chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chr23,chr24,chr25"
# number of threads for juicertools arrowhead
juicer_arrowhead_threads: 8
#select the normalization method used for detecting TADs (NONE/VC/VC_SQRT/KR)
juicer_arrowhead_normalization: "KR"
juicer_arrowhead_sliding_window: 2000
